# Generated by Django 2.2 on 2019-05-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockDataBase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockBasicTradeCal',
            new_name='Stock_Basic_Trade_Cal',
        ),
    ]
