# Generated by Django 2.2 on 2019-05-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockDataBase', '0002_auto_20190502_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Basic_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('truename', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=36)),
                ('authority', models.CharField(max_length=8)),
                ('deleted', models.CharField(max_length=5)),
            ],
        ),
    ]
