# Generated by Django 2.2 on 2019-05-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockDataBase', '0003_stock_basic_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Basic_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=12)),
                ('exchange', models.CharField(max_length=8)),
                ('chairman', models.CharField(max_length=30)),
                ('manager', models.CharField(max_length=30)),
                ('secretary', models.CharField(max_length=30)),
                ('reg_capital', models.CharField(max_length=20)),
                ('setup_date', models.CharField(max_length=12)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('introduction', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('office', models.CharField(max_length=30)),
                ('employees', models.CharField(max_length=50)),
                ('main_business', models.CharField(max_length=255)),
                ('business_scope', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Basic_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=12)),
                ('symbol', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=255)),
                ('enname', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=30)),
                ('exchange', models.CharField(max_length=8)),
                ('curr_type', models.CharField(max_length=30)),
                ('list_status', models.CharField(max_length=8)),
                ('list_date', models.CharField(max_length=12)),
                ('delist_date', models.CharField(max_length=12)),
                ('is_hs', models.CharField(max_length=8)),
            ],
        ),
    ]
