# Generated by Django 2.2 on 2019-05-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('nameinfo', models.CharField(max_length=1000)),
                ('feature', models.CharField(max_length=1000)),
                ('livemethod', models.CharField(max_length=1000)),
                ('feednn', models.CharField(max_length=1000)),
                ('feedmethod', models.CharField(max_length=1000)),
            ],
        ),
    ]
